---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    refresh:
      enable: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    refresh:
      enable: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    refresh:
      enable: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761,http://127.0.0.1:8762
